language: ruby
rvm:
  - 2.2.0
  - 2.1.0
 
notifications:
  irc:
    channels:
      - "chat.freenode.net#nanoc"
    template:
      - "%{repository}/%{branch} %{commit} %{author}: %{message}"
    use_notice: true
    skip_join: true
